name: PR

on:
  issue_comment:
    types: [ 'created' ]
  pull_request:
    types: ["opened", "reopened", "synchronize", "ready_for_review"]
    branches: ["**", "main"]
    paths:
      - "**" # all files otherwise excludes wont work
      - "!**/**/*.md" # ignore markdown files
      - "!demo/**" # ignore demos folder
      - "!sample/**" # ignore samples folder
      - "!example/**" # ignore examples folder

jobs:
  trigger-checks:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      conformance-comment: ${{ steps.conformance_comment_trigger.outputs.triggered == 'true' }}
      v2: ${{ steps.conformance_comment_trigger.outputs.arguments)[0] }}
      v2j: ${{ fromJson(steps.conformance_comment_trigger.outputs.arguments)[0]) }}
    steps:
      - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        id: conformance_comment_trigger
        if: ${{ github.event.issue.pull_request }}
        with:
          trigger: '/test-conformance **'
          reaction: eyes
          allow_arguments: true
        env:
          GITHUB_TOKEN: '${{ secrets.PAT_CI_GHAX }}'

  setup-vars:
    uses: MirantisContainers/shared-workflows/.github/workflows/vars.yml@v0.0.1
    with:
      env-config-path: .github/development.env # No values are actually used ATM
  integration-by-comment:
    needs: [trigger-checks]
    outputs:
      output_1: ${{ needs.trigger-checks.outputs.output_1 }}
    if: ${{ needs.trigger-checks.outputs.conformance-comment == 'true' }}
    steps:
      - env:
          OUTPUT2: ${{outputs.output_1}}
        run: echo "$OUTPUT2" {{ needs.trigger-checks.outputs.v2 }} {{ needs.trigger-checks.outputs.v2j }}
