name: Reaction Failure

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      node_id:
        description: 'Comment Node ID'
        required: true
        type: string

jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: |
          gh api graphql --silent --raw-field query="mutation AddReaction {addReaction(input:{subjectId:\"$NODE_ID\",content:"-1"}){reaction{content}subject{id}}}"
          gh api graphql --silent --raw-field query="mutation RemoveReaction {removeReaction(input:{subjectId:\"$NODE_ID\",content:EYES}){reaction{content}subject{id}}}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_CI_GHAX }}
          PR_NUMBER: ${{ inputs.pr_number }}
          NODE_ID: ${{ inputs.node_id }}
